version: '3.8'

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '8080:8080' # 왼쪽: 호스트, 오른쪽: 컨테이너
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
    # command: sh -c "pnpm run migration:run && node dist/src/main" # 필요시

  nginx:
    image: nginx:latest
    container_name: nginx-ssl
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/etc/nginx/cert
    ports:
      - '443:443'
    depends_on:
      - nest-app
